### PR TITLE
Simplified Chinese localization

### PR DESCRIPTION
**Pull request by Animuses**
Some fonts in the game such as "bank", "bankshadow", "bankshadowmore" are frequntely used (hudfont), but these fonts don't have chinese character support, it will trun chinese characters into blocks. To fix this problem, I find out that change fonts in lua scripts like using "objective" will solve the problem, maybe we can change something to fix this

### CODE REVIEW

**Comment by fedddddd** [comment]
Fixed the issue in [e28dd09](https://github.com/fedddddd/h2-mod/commit/e28dd09cba9991940e942b286c7cb9a230c91655).  
Did you translate these manually or did you dump them from mw2? There's some strings that are still in english

**Comment by Animuses** [comment]
Original mw2 did not have chinese translation, I translate them manually. Strings that are still in english is basically pmc part which is not used in this mod. If you think these contents needs to be translated, I will translate them and update this

**Comment by Animuses** [comment]
> Fixed the font issue in [e28dd09](https://github.com/fedddddd/h2-mod/commit/e28dd09cba9991940e942b286c7cb9a230c91655). Did you translate these manually or did you dump them from mw2? There's some strings that are still in english

Original mw2 did not have chinese translation, I translate them manually. Strings that are still in english is basically pmc part which is not used in this mod. If you think these contents needs to be translated, I will translate them and update this

**Comment by fedddddd** [comment]
Oh ok, didn't know that.  
Most of the pmc stuff isn't used so you don't have to translate it all but you need to add these:
PMC_HQ_RECOVERING_INTEL  
PMC_OBJECTIVE_ABORT_CODES  
PMC_OBJECTIVE_KILL_ENEMIES_REMAINING  
PMC_OBJECTIVE_KILL_ENEMIES  
PMC_OBJECTIVE_EXTRACT

**Comment by Animuses** [comment]
Strings updated. Thank you for the check.

**Pull request merged**
